### PR TITLE
Write up instructions on how to share home-brew across accounts on MacOS

### PR DESCRIPTION
**Pull request by nicholasjhenry**
Just add it in as a comment for now.

### CODE REVIEW

**Comment by nicholasjhenry** [comment]
@bokay Can you please review the guide I have added here when you create your pairing account on your machine and make any changes required to this PR.

Also I've noticed a message we are getting with `zsh` when we login in. Can you please update the guide on how to resolve that? Thanks!

```
[oh-my-zsh] Insecure completion-dependent directories detected:
drwxrwxr-x   7 admin        admin  224 26 Nov 12:33 /usr/local/share/zsh
drwxrwxr-x  10 admin        admin  320 26 Nov 12:36 /usr/local/share/zsh/site-functions
lrwxr-xr-x   1 briangracie  admin   56 26 Nov 12:21 /usr/local/share/zsh/site-functions/_git -> ../../../Cellar/git/2.19.2/share/zsh/site-functions/_git
lrwxr-xr-x   1 briangracie  admin   55 26 Nov 12:36 /usr/local/share/zsh/site-functions/_hub -> ../../../Cellar/hub/2.6.0/share/zsh/site-functions/_hub

[oh-my-zsh] For safety, we will not load completions from these directories until
[oh-my-zsh] you fix their permissions and ownership and restart zsh.
[oh-my-zsh] See the above list for directories with group or other writability.

[oh-my-zsh] To fix your permissions you can do so by disabling
[oh-my-zsh] the write permission of "group" and "others" and making sure that the
[oh-my-zsh] owner of these directories is either root or your current user.
[oh-my-zsh] The following command may help:
[oh-my-zsh]     compaudit | xargs chmod g-w,o-w

[oh-my-zsh] If the above didn't help or you want to skip the verification of
[oh-my-zsh] insecure directories you can set the variable ZSH_DISABLE_COMPFIX to
[oh-my-zsh] "true" before oh-my-zsh is sourced in your zshrc file.
```

**Comment by bokay** [comment]
Exactly that. Keeping homebrew manipulation to the owner of the machine as the bin files will be shared anyway regardless of the user.
One can use `login owner_handle` in order to perform the operation quickly without switching session at the OS level.

Regarding zsh, I'm not sure if the issue I had will be repeated on other instances as all I had to do was to reinstall zsh on the pairing machine, and also because I had no issues regarding zsh before tweaking homebrew.

**Comment by civilcode-pairing** [comment]
Here are the last commands I run on my machine when the issue was solved:
```
brew link --overwrite --dry-run zsh
brew install zsh
brew link zsh
brew link --overwrite zsh
brew install zsh
```

I can't remember if and why I had to run the `brew install` twice though.

**Comment by nicholasjhenry** [comment]
Thank you @bokay, I managed to get this working.

https://github.com/civilcode/playbook/pull/90#issuecomment-451971051

**Comment by nicholasjhenry** [comment]
This PR updates our Playbook for managing multiple user (developer) accounts on the same machine. We require an update to the `laptop` script: https://github.com/civilcode/laptop/issues/35

This is on hold until it is completed and merged.

**Pull request merged**
